title: ac-predictor
baseurl: /
url: https://ac-predictor.com
repository: https://github.com/key-moon/ac-predictor

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - ".gitignore"
  - CNAME
  - /js/src/*
  - package.json
  - package-lock.json
  - tsconfig.json
